### ISSUE TITLE
Unable to compile on fresh install of M2 Ventura

### ISSUE THREAD

**Issue by amizzo87** [Vargol/ffmpeg-apple-arm64-build#11]
Not sure what info is helpful here, fresh install of MacOS 13.2 with xcode-tools on a MacBook Air M2, but fails at compiling `libass` with the following:

```checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/anthonyizzo/Development/ffmpeg-apple-arm64-build/libass/libass-0.15.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
+ checkStatus 77 'configuration of libass failed'
+ '[' 77 -ne 0 ']'
+ echo 'check failed: configuration of libass failed'
check failed: configuration of libass failed
+ exit 1```

Any ideas?

**Comment by Vargol** [comment]
Not on 13.2 yet as I use the M1 for stuff that I'm not risking a beta OS with :-)

Can you attach your config.log file from building libass

It should be at
/Users/anthonyizzo/Development/ffmpeg-apple-arm64-build/libass/libass-0.15.1/config.log

libass  failing to configure is usually an issue from brotli changing stuff, they change the name and location of their static libs every now and again.

I'm running a fresh build on my 13.1 M1 to see if I can duplicate the issue.

**Comment by Vargol** [comment]
okay I think I've fixed it, assuming the issue I had was the same as the one you do.
Brotli tidied up their build, which meant my configure didn't build the static libraries anymore.
I've fixed the master branch to build both properly.

**Comment by amizzo87** [comment]
Wow thanks for the quick fix - confirmed that change worked on my end as well :)
