### ISSUE TITLE
check failed: build ffmpeg

### ISSUE THREAD

**Issue by sevenrats** [Vargol/ffmpeg-apple-arm64-build#15]
I'm running on a M2 mini I got in march and this build script fails for me at the ```compile ffmpeg``` phase.
Here is the build-ffmpeg.log
https://pastebin.com/raw/yj76pu8s

**Comment by Vargol** [comment]
Okay, looks like STV-AV1 has made some changes that make it incompatible with the version of ffmpeg being built, guess its time to update.

What I'm going to do is update to the same version that the topazlabs version requires.

echoSection "compile ffmpeg with topaz"
$SCRIPT_DIR/build-ffmpeg-topaz.sh "$SCRIPT_DIR" "$WORKING_DIR" "$TOOL_DIR" "$OUT_DIR" "$CPUS" "6.0.0.6" > "$WORKING_DIR/build-ffmpeg-topaz.log" 2>&1
else
echoSection "compile ffmpeg"
$SCRIPT_DIR/build-ffmpeg.sh "$SCRIPT_DIR" "$WORKING_DIR" "$TOOL_DIR" "$OUT_DIR" "$CPUS" "5.1" > "$WORKING_DIR/build-ffmpeg.log" 2>&1
fi

becomes

echoSection "compile ffmpeg with topaz"
$SCRIPT_DIR/build-ffmpeg-topaz.sh "$SCRIPT_DIR" "$WORKING_DIR" "$TOOL_DIR" "$OUT_DIR" "$CPUS" "6.0.0.6" > "$WORKING_DIR/build-ffmpeg-topaz.log" 2>&1
else
echoSection "compile ffmpeg"
$SCRIPT_DIR/build-ffmpeg.sh "$SCRIPT_DIR" "$WORKING_DIR" "$TOOL_DIR" "$OUT_DIR" "$CPUS" "6.0.0.6" > "$WORKING_DIR/build-ffmpeg.log" 2>&1
fi

I'll run some tests and see if I can duplicate you issue and then fix it with that change

**Comment by Vargol** [comment]
Yea, the update worked, I committing it to the git repo and made a new release based on the new version.

**Comment by sevenrats** [comment]
that did it.  thanks for the quick fix!
