### ISSUE TITLE
Feature Request: bring avisynth branch up to date

### ISSUE THREAD

**Issue by sevenrats** [Vargol/ffmpeg-apple-arm64-build#16]
AVISynth+ appears to provide native apple silicon support.  It's just a matter of knowing where avisynth+ puts its headers and where ffmpeg looks for them.  I installed AVISynth+ and modified build-ffmpeg.sh to include the --enable-avisynth flag, but it doesn't seem to make it into the binary.  Any idea why?

**Comment by Vargol** [comment]
There's already a branch that links in avisynth+. its a little out of date compared to main though so will probably need the ffmpeg version boosting like I did earlier today.

From recollection AviSynth+ is a weird one as it doesn't actually link AviSynth but uses run time loading of the library and you need to run ffmpeg from the folder where the library is (or a soft link to it) as macOS now has tight restrictions on where it'll do run time loading from.

**Comment by sevenrats** [comment]
this is definitely what i was missing, thank you!
