### ISSUE TITLE
Push the patch upstream?

### ISSUE THREAD

**Issue by psommerfeld** [Vargol/ffmpeg-apple-arm64-build#3]
I'm very new to looking at ffmpeg code.
Could this NEON patch not be pushed upstream to videolan/x265 repo?

**Comment by Vargol** [comment]
Yes it could, in fact it was merged at the bitbucket repository a few months ago, but not is not in any release versions yet they also broke multi-lib building while doing it.

Sadly for some reason none of the mirrors have been updated in ages
Github's videolan/x265 is a year out of date. 
the Mercurial repo at hg.videolan.org is 6 months out of date.

If you change to the x265_from_master branch you can build from the bitbucket repo, but that requires quite a decent patch itself and that patch conflicts with other proposed patches that may be even faster than the apple patch.
It's all in a bit of a mess ATM.
