### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Troubadoure** [Vargol/ffmpeg-apple-arm64-build#5]
Thanks for the script but I keep getting a build fail on compiling free type.

CMakeError.log
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Library/Developer/CommandLineTools/usr/bin/cc 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Running macOS 12.2 on Mac Mini M1
Xcode 13.2.1
curl 7.77.0 (x86_64-apple-darwin21.0) libcurl/7.77.0 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.42.0
GNU Make 3.81
git version 2.32.0 (Apple Git-132)

**Comment by Vargol** [comment]
I'll have a look see if the make guys have broke their build.. 

I'd guess it may be the use of GNU make, the script is designed to work with just the Xcode command line tools installed.
I'f you've recently updated Xcode but haven't run it its worth launching it and see if it prompts for the extra's install.

**Comment by Troubadoure** [comment]
Thanks for the quick response. I ran it with just the Xcode cli tools and got the same error. installed Xcode and re-ran and opened Xcode accept eula and re-ran. All produced the same error

**Comment by Vargol** [comment]
Gaah, looks like it a macOS 12.2 issue

https://discourse.cmake.org/t/cmake-not-working-after-update-do-big-sur/2546

**Comment by Vargol** [comment]
The cmake build is still working on macOS 12.1.

Unfortunately that it looks like freetype has broke something, I really should get a stable version of the script that builds known working versions.

**Comment by Troubadoure** [comment]
Thanks - looks like thats the issue. I tried a fix of 

```
$ sudo rm -rf /Library/Developer/CommandLineTools
$ xcode-select --install
```

as suggested in that link but now seem to be stuck in a constant update cycle.

**Comment by mshoe007** [comment]
FYI, MacOS 12.2, XCode 13.2.1, MacBook Pro M1. I cloned the respository, typed 'build.sh' and the build completed with no errors.

mbpro:ffmpeg-5.0 > ./ffmpeg
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.30)
  configuration: --prefix=/Users/mbs/src/git/Vargol/ffmpeg-apple-arm64-build/out/out --enable-gpl --pkg-config-flags=--static --pkg-config=/Users/mbs/src/git/Vargol/ffmpeg-apple-arm64-build/out/tool/bin/pkg-config --enable-libaom --enable-libopenh264 --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-neon --enable-runtime-cpudetect --enable-audiotoolbox --enable-videotoolbox --enable-libvorbis --enable-libsvtav1 --enable-libass --enable-lto --enable-opencl
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by smeyfroi** [comment]
Also here to confirm a clean build on MacBook Pro (13-inch, M1, 2020), MacOS 12.4 (21F79) 👍

Think this issue can be closed now?

**Comment by MuZiLee** [comment]
Hello!
Is Intel normal except for M1?
