### ISSUE TITLE
Adding ffplay to the build

### ISSUE THREAD

**Issue by suvl** [Vargol/ffmpeg-apple-arm64-build#6]
Hey there. Is it possible to add the `ffplay` to the build's output?

I have tried cloning the SDL library from [here](https://github.com/libsdl-org/SDL), building it to the `tools/` folder and setting `--enable-sdl2` in the `build-ffmpeg.sh`'s `./configure` step, but it still won't compile that binary. Any help?

I can set a branch with where I got if you'd like, and even write a `build-SDL.sh` script.

**Comment by Vargol** [comment]
Hi, I sems to have got it working without to much hassle

I used the following as build-sdl2.sh (had to rename it to .txt to upload it )
[build-sdl2.txt](https://github.com/Vargol/ffmpeg-apple-arm64-build/files/9312508/build-sdl2.txt)

and modified build.sh with

```
START_TIME=$(currentTimeInSeconds)
echoSection "compile sdl2"
$SCRIPT_DIR/build-sdl2.sh "$SCRIPT_DIR" "$WORKING_DIR" "$TOOL_DIR" "$CPUS" "xxxx" > "$WORKING_DIR/build-sdl2.log" 2>&1
checkStatus $? "build sdl2"
echoDurationInSections $START_TIME
```

**Comment by suvl** [comment]
I also confirm that works 👍🏽 I'd PR but since you already have it in a dev branch I'll just go ahead and close this issue. Many thanks!
